### ISSUE TITLE
CSS remake

### ISSUE THREAD

**Issue by Isigar** [drcallaway/chrome-graphql-playground#1]
Hello, I love using your extension for chrome but... Buttons are so ugly... Please can you add to button class `    border: 1px solid rgba(200,200,200,0.3);` it will look better and its one line of code and for delete whitespace around app add to <body> tag margin:0; style. Thanks for response :) :+1:

**Comment by tacallaway** [comment]
Hi Isigar. Thanks for the feedback but, unfortunately, I just made the plugin that wraps the GraphQL Playground app. That app is hosted in a different repo so you should make your suggestion here: https://github.com/prisma/graphql-playground

**Comment by drcallaway** [comment]
Hi Isigar. Thanks for the feedback but, unfortunately, I just made the plugin that wraps the GraphQL Playground app. That app is hosted in a different repo so you should make your suggestion here: https://github.com/prisma/graphql-playground
