### ISSUE TITLE
Select multiple query to start bug

### ISSUE THREAD

**Issue by Isigar** [drcallaway/chrome-graphql-playground#2]
Hello,
when you insert multiple query with different name its problem with start button. Missing CSS or a href link.
https://imgur.com/a/mMCt3K9

**Comment by drcallaway** [comment]
Thanks @Isigar. However, this repo is just for the Chrome extension that I built for the GraphQL Playground application. This issue sounds like it needs to be directed to the repo for that project: https://github.com/prisma/graphql-playground
